{"trial_id": "00", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 3, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_0", "default": 0.0, "conditions": [], "min_value": 0.0, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 0.0001, "conditions": [], "min_value": 0.0001, "max_value": 0.01, "step": null, "sampling": "log"}}], "values": {"num_layers": 1, "units_0": 96, "dropout_0": 0.1, "learning_rate": 0.007387949622995673}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node compile_loss/mean_squared_error/sub defined at (most recent call last):\n  File \"c:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\playground\\Lotto\\compare2digits.py\", line 150, in <module>\n\n  File \"c:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\playground\\Lotto\\compare2digits.py\", line 98, in main\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 234, in search\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 117, in error_handler\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\backend\\tensorflow\\trainer.py\", line 368, in fit\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\backend\\tensorflow\\trainer.py\", line 216, in function\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\backend\\tensorflow\\trainer.py\", line 129, in multi_step_on_iterator\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\backend\\tensorflow\\trainer.py\", line 110, in one_step_on_data\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\backend\\tensorflow\\trainer.py\", line 59, in train_step\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\trainers\\trainer.py\", line 399, in _compute_loss\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\trainers\\trainer.py\", line 367, in compute_loss\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\trainers\\compile_utils.py\", line 692, in __call__\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\trainers\\compile_utils.py\", line 701, in call\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\losses\\loss.py\", line 67, in __call__\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\losses\\losses.py\", line 33, in call\n\n  File \"C:\\Users\\Sirin\\Documents\\GitHub\\heartrhythmbox\\.venv\\Lib\\site-packages\\keras\\src\\losses\\losses.py\", line 1674, in mean_squared_error\n\nIncompatible shapes: [32] vs. [32,10,2]\n\t [[{{node compile_loss/mean_squared_error/sub}}]] [Op:__inference_multi_step_on_iterator_2955]\n"}